# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging

import cupy as cp
import holoscan


class ADTFUnpackOp(holoscan.core.Operator):

    JET_LUT_U8 = bytes(
        [
            0x00,
            0x00,
            0x7F,
            0x00,
            0x00,
            0x84,
            0x00,
            0x00,
            0x88,
            0x00,
            0x00,
            0x8D,
            0x00,
            0x00,
            0x91,
            0x00,
            0x00,
            0x96,
            0x00,
            0x00,
            0x9A,
            0x00,
            0x00,
            0x9F,
            0x00,
            0x00,
            0xA3,
            0x00,
            0x00,
            0xA8,
            0x00,
            0x00,
            0xAC,
            0x00,
            0x00,
            0xB1,
            0x00,
            0x00,
            0xB6,
            0x00,
            0x00,
            0xBA,
            0x00,
            0x00,
            0xBF,
            0x00,
            0x00,
            0xC3,
            0x00,
            0x00,
            0xC8,
            0x00,
            0x00,
            0xCC,
            0x00,
            0x00,
            0xD1,
            0x00,
            0x00,
            0xD5,
            0x00,
            0x00,
            0xDA,
            0x00,
            0x00,
            0xDE,
            0x00,
            0x00,
            0xE3,
            0x00,
            0x00,
            0xE8,
            0x00,
            0x00,
            0xEC,
            0x00,
            0x00,
            0xF1,
            0x00,
            0x00,
            0xF5,
            0x00,
            0x00,
            0xFA,
            0x00,
            0x00,
            0xFE,
            0x00,
            0x00,
            0xFF,
            0x00,
            0x00,
            0xFF,
            0x00,
            0x00,
            0xFF,
            0x00,
            0x00,
            0xFF,
            0x00,
            0x04,
            0xFF,
            0x00,
            0x08,
            0xFF,
            0x00,
            0x0C,
            0xFF,
            0x00,
            0x10,
            0xFF,
            0x00,
            0x14,
            0xFF,
            0x00,
            0x18,
            0xFF,
            0x00,
            0x1C,
            0xFF,
            0x00,
            0x20,
            0xFF,
            0x00,
            0x24,
            0xFF,
            0x00,
            0x28,
            0xFF,
            0x00,
            0x2C,
            0xFF,
            0x00,
            0x30,
            0xFF,
            0x00,
            0x34,
            0xFF,
            0x00,
            0x38,
            0xFF,
            0x00,
            0x3C,
            0xFF,
            0x00,
            0x40,
            0xFF,
            0x00,
            0x44,
            0xFF,
            0x00,
            0x48,
            0xFF,
            0x00,
            0x4C,
            0xFF,
            0x00,
            0x50,
            0xFF,
            0x00,
            0x54,
            0xFF,
            0x00,
            0x58,
            0xFF,
            0x00,
            0x5C,
            0xFF,
            0x00,
            0x60,
            0xFF,
            0x00,
            0x64,
            0xFF,
            0x00,
            0x68,
            0xFF,
            0x00,
            0x6C,
            0xFF,
            0x00,
            0x70,
            0xFF,
            0x00,
            0x74,
            0xFF,
            0x00,
            0x78,
            0xFF,
            0x00,
            0x7C,
            0xFF,
            0x00,
            0x80,
            0xFF,
            0x00,
            0x84,
            0xFF,
            0x00,
            0x88,
            0xFF,
            0x00,
            0x8C,
            0xFF,
            0x00,
            0x90,
            0xFF,
            0x00,
            0x94,
            0xFF,
            0x00,
            0x98,
            0xFF,
            0x00,
            0x9C,
            0xFF,
            0x00,
            0xA0,
            0xFF,
            0x00,
            0xA4,
            0xFF,
            0x00,
            0xA8,
            0xFF,
            0x00,
            0xAC,
            0xFF,
            0x00,
            0xB0,
            0xFF,
            0x00,
            0xB4,
            0xFF,
            0x00,
            0xB8,
            0xFF,
            0x00,
            0xBC,
            0xFF,
            0x00,
            0xC0,
            0xFF,
            0x00,
            0xC4,
            0xFF,
            0x00,
            0xC8,
            0xFF,
            0x00,
            0xCC,
            0xFF,
            0x00,
            0xD0,
            0xFF,
            0x00,
            0xD4,
            0xFF,
            0x00,
            0xD8,
            0xFF,
            0x00,
            0xDC,
            0xFE,
            0x00,
            0xE0,
            0xFA,
            0x00,
            0xE4,
            0xF7,
            0x02,
            0xE8,
            0xF4,
            0x05,
            0xEC,
            0xF1,
            0x08,
            0xF0,
            0xED,
            0x0C,
            0xF4,
            0xEA,
            0x0F,
            0xF8,
            0xE7,
            0x12,
            0xFC,
            0xE4,
            0x15,
            0xFF,
            0xE1,
            0x18,
            0xFF,
            0xDD,
            0x1C,
            0xFF,
            0xDA,
            0x1F,
            0xFF,
            0xD7,
            0x22,
            0xFF,
            0xD4,
            0x25,
            0xFF,
            0xD0,
            0x29,
            0xFF,
            0xCD,
            0x2C,
            0xFF,
            0xCA,
            0x2F,
            0xFF,
            0xC7,
            0x32,
            0xFF,
            0xC3,
            0x36,
            0xFF,
            0xC0,
            0x39,
            0xFF,
            0xBD,
            0x3C,
            0xFF,
            0xBA,
            0x3F,
            0xFF,
            0xB7,
            0x42,
            0xFF,
            0xB3,
            0x46,
            0xFF,
            0xB0,
            0x49,
            0xFF,
            0xAD,
            0x4C,
            0xFF,
            0xAA,
            0x4F,
            0xFF,
            0xA6,
            0x53,
            0xFF,
            0xA3,
            0x56,
            0xFF,
            0xA0,
            0x59,
            0xFF,
            0x9D,
            0x5C,
            0xFF,
            0x9A,
            0x5F,
            0xFF,
            0x96,
            0x63,
            0xFF,
            0x93,
            0x66,
            0xFF,
            0x90,
            0x69,
            0xFF,
            0x8D,
            0x6C,
            0xFF,
            0x89,
            0x70,
            0xFF,
            0x86,
            0x73,
            0xFF,
            0x83,
            0x76,
            0xFF,
            0x80,
            0x79,
            0xFF,
            0x7D,
            0x7C,
            0xFF,
            0x79,
            0x80,
            0xFF,
            0x76,
            0x83,
            0xFF,
            0x73,
            0x86,
            0xFF,
            0x70,
            0x89,
            0xFF,
            0x6C,
            0x8D,
            0xFF,
            0x69,
            0x90,
            0xFF,
            0x66,
            0x93,
            0xFF,
            0x63,
            0x96,
            0xFF,
            0x5F,
            0x9A,
            0xFF,
            0x5C,
            0x9D,
            0xFF,
            0x59,
            0xA0,
            0xFF,
            0x56,
            0xA3,
            0xFF,
            0x53,
            0xA6,
            0xFF,
            0x4F,
            0xAA,
            0xFF,
            0x4C,
            0xAD,
            0xFF,
            0x49,
            0xB0,
            0xFF,
            0x46,
            0xB3,
            0xFF,
            0x42,
            0xB7,
            0xFF,
            0x3F,
            0xBA,
            0xFF,
            0x3C,
            0xBD,
            0xFF,
            0x39,
            0xC0,
            0xFF,
            0x36,
            0xC3,
            0xFF,
            0x32,
            0xC7,
            0xFF,
            0x2F,
            0xCA,
            0xFF,
            0x2C,
            0xCD,
            0xFF,
            0x29,
            0xD0,
            0xFF,
            0x25,
            0xD4,
            0xFF,
            0x22,
            0xD7,
            0xFF,
            0x1F,
            0xDA,
            0xFF,
            0x1C,
            0xDD,
            0xFF,
            0x18,
            0xE0,
            0xFF,
            0x15,
            0xE4,
            0xFF,
            0x12,
            0xE7,
            0xFF,
            0x0F,
            0xEA,
            0xFF,
            0x0C,
            0xED,
            0xFF,
            0x08,
            0xF1,
            0xFC,
            0x05,
            0xF4,
            0xF8,
            0x02,
            0xF7,
            0xF4,
            0x00,
            0xFA,
            0xF0,
            0x00,
            0xFE,
            0xED,
            0x00,
            0xFF,
            0xE9,
            0x00,
            0xFF,
            0xE5,
            0x00,
            0xFF,
            0xE2,
            0x00,
            0xFF,
            0xDE,
            0x00,
            0xFF,
            0xDA,
            0x00,
            0xFF,
            0xD7,
            0x00,
            0xFF,
            0xD3,
            0x00,
            0xFF,
            0xCF,
            0x00,
            0xFF,
            0xCB,
            0x00,
            0xFF,
            0xC8,
            0x00,
            0xFF,
            0xC4,
            0x00,
            0xFF,
            0xC0,
            0x00,
            0xFF,
            0xBD,
            0x00,
            0xFF,
            0xB9,
            0x00,
            0xFF,
            0xB5,
            0x00,
            0xFF,
            0xB1,
            0x00,
            0xFF,
            0xAE,
            0x00,
            0xFF,
            0xAA,
            0x00,
            0xFF,
            0xA6,
            0x00,
            0xFF,
            0xA3,
            0x00,
            0xFF,
            0x9F,
            0x00,
            0xFF,
            0x9B,
            0x00,
            0xFF,
            0x98,
            0x00,
            0xFF,
            0x94,
            0x00,
            0xFF,
            0x90,
            0x00,
            0xFF,
            0x8C,
            0x00,
            0xFF,
            0x89,
            0x00,
            0xFF,
            0x85,
            0x00,
            0xFF,
            0x81,
            0x00,
            0xFF,
            0x7E,
            0x00,
            0xFF,
            0x7A,
            0x00,
            0xFF,
            0x76,
            0x00,
            0xFF,
            0x73,
            0x00,
            0xFF,
            0x6F,
            0x00,
            0xFF,
            0x6B,
            0x00,
            0xFF,
            0x67,
            0x00,
            0xFF,
            0x64,
            0x00,
            0xFF,
            0x60,
            0x00,
            0xFF,
            0x5C,
            0x00,
            0xFF,
            0x59,
            0x00,
            0xFF,
            0x55,
            0x00,
            0xFF,
            0x51,
            0x00,
            0xFF,
            0x4D,
            0x00,
            0xFF,
            0x4A,
            0x00,
            0xFF,
            0x46,
            0x00,
            0xFF,
            0x42,
            0x00,
            0xFF,
            0x3F,
            0x00,
            0xFF,
            0x3B,
            0x00,
            0xFF,
            0x37,
            0x00,
            0xFF,
            0x34,
            0x00,
            0xFF,
            0x30,
            0x00,
            0xFF,
            0x2C,
            0x00,
            0xFF,
            0x28,
            0x00,
            0xFF,
            0x25,
            0x00,
            0xFF,
            0x21,
            0x00,
            0xFF,
            0x1D,
            0x00,
            0xFF,
            0x1A,
            0x00,
            0xFF,
            0x16,
            0x00,
            0xFE,
            0x12,
            0x00,
            0xFA,
            0x0F,
            0x00,
            0xF5,
            0x0B,
            0x00,
            0xF1,
            0x07,
            0x00,
            0xEC,
            0x03,
            0x00,
            0xE8,
            0x00,
            0x00,
            0xE3,
            0x00,
            0x00,
            0xDE,
            0x00,
            0x00,
            0xDA,
            0x00,
            0x00,
            0xD5,
            0x00,
            0x00,
            0xD1,
            0x00,
            0x00,
            0xCC,
            0x00,
            0x00,
            0xC8,
            0x00,
            0x00,
            0xC3,
            0x00,
            0x00,
            0xBF,
            0x00,
            0x00,
            0xBA,
            0x00,
            0x00,
            0xB6,
            0x00,
            0x00,
            0xB1,
            0x00,
            0x00,
            0xAC,
            0x00,
            0x00,
            0xA8,
            0x00,
            0x00,
            0xA3,
            0x00,
            0x00,
            0x9F,
            0x00,
            0x00,
            0x9A,
            0x00,
            0x00,
            0x96,
            0x00,
            0x00,
            0x91,
            0x00,
            0x00,
            0x8D,
            0x00,
            0x00,
            0x88,
            0x00,
            0x00,
            0x84,
            0x00,
            0x00,
            0x7F,
            0x00,
            0x00,
        ]
    )

    def __init__(self, *args, no_of_planes=3, width, height, **kwargs):
        super().__init__(*args, **kwargs)
        self._no_of_planes = no_of_planes
        lut_np = cp.frombuffer(self.JET_LUT_U8, dtype=cp.uint8).reshape(256, 3)
        self._jet_lut = cp.asarray(lut_np)  # GPU resident

        self._width = width
        self._height = height
        self._save = 1

    def setup(self, spec):
        logging.info("ADTFUnpackOp setup")
        spec.input("input")
        spec.output("output")

    def start(self):
        pass

    def stop(self):
        pass

    def converttojetimage(self, depth_u16):
        # depth_u16: (H, W), uint16

        depth_norm = cp.clip(
            (depth_u16.astype(cp.float32) / 4000.0) * 255, 0, 255
        ).astype(cp.uint8)

        rgb = self._jet_lut[depth_norm]
        # shape: (H, W, 3), dtype=uint8
        return rgb

    def convert_to_grayscale(self, image, max_val=4096.0):
        # Normalize to 0-255 using the given full-scale value
        image_normalized = cp.clip(
            image.astype(cp.float32) * 255.0 / max_val, 0, 255
        ).astype(cp.uint8)
        image_grayscale = cp.repeat(image_normalized[:, :, None], 3, axis=2)
        return image_grayscale

    def compute(self, op_input, op_output, context):
        # Get input message
        in_message = op_input.receive("input")
        msg = in_message.get("")
        cp_frame = cp.asarray(msg)

        # CsiToBayerOp outputs uint16 with pixel value in the high byte.
        # Extract the 8-bit payload from each uint16 (mirrors shift_and_cast_kernel).
        cp_frame_u8 = (cp_frame >> 8).astype(cp.uint8)

        # -----------------------------------------------------------------------
        # Unpack ADI ToF subframe-planar layout (mirrors unpack_kernel in .cu):
        #
        #   Subframe 1 (N×3 bytes): [D_L][D_H][C] for each of N = H×W pixels
        #   Subframe 2 (N×2 bytes): [AB_L][AB_H] for each of N pixels
        #
        # Total = N×5 bytes (NOT 5 interleaved bytes per pixel).
        # -----------------------------------------------------------------------
        N = self._height * self._width
        raw_flat = cp_frame_u8.reshape(-1)  # flatten to 1D (N*5 bytes)

        # Subframe 1: depth (uint16 LE) + confidence (uint8) — 3 bytes per pixel
        sf1 = raw_flat[:N * 3].reshape(N, 3)
        depth = (sf1[:, 0].astype(cp.uint16) | (sf1[:, 1].astype(cp.uint16) << 8)
                 ).reshape(self._height, self._width)
        conf  = sf1[:, 2].astype(cp.uint16).reshape(self._height, self._width)

        # Subframe 2: active brightness (uint16 LE) — 2 bytes per pixel
        sf2 = raw_flat[N * 3:N * 5].reshape(N, 2)
        active_brightness = (sf2[:, 0].astype(cp.uint16) | (sf2[:, 1].astype(cp.uint16) << 8)
                             ).reshape(self._height, self._width)

        if self._save == 1:
            # dump or save one frame of data, executed only once
            cp_frame_u8.astype("uint8").tofile("dump.bin")
            depth.astype("uint16").tofile("depth.bin")
            conf.astype("uint16").tofile("conf.bin")
            active_brightness.astype("uint16").tofile("ab.bin")
            self._save = 0

        depth_c            = self.converttojetimage(depth)
        active_brightness_c = self.convert_to_grayscale(active_brightness, max_val=4096.0)
        conf_c             = self.convert_to_grayscale(conf, max_val=255.0)

        if self._no_of_planes == 1:
            op_output.emit({"Depth": cp_frame_u8}, "output")
        elif self._no_of_planes == 2:
            op_output.emit({"Depth": depth_c, "ActiveBrightness": active_brightness_c}, "output")
        elif self._no_of_planes == 3:
            op_output.emit(
                {"Depth": depth_c, "ActiveBrightness": active_brightness_c, "Conf": conf_c},
                "output",
            )
